---
require: rubocop-performance

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable         # enable new upcoming cops for rubocop
  Exclude:
<<<<<<< HEAD
    - _snippets/**/*
=======
    - _snippets/*
>>>>>>> e4faaca (Hardens database and secures configuration)

# ignore block length where unavoidable (e.g., framework requires it)
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/* # Minitest's nested test structure requires large blocks
    # - app/controllers/*.rb # Roda's nested controllers require large blocks
    # - Rakefile # Rake namespaces produce large blocks

Security/YAMLLoad:
  Enabled: true
  Exclude:
    - spec/**/*

# Style/HashSyntax:
#   Enabled: true
#   Exclude:
#     - Rakefile

Style/SymbolArray:
  Enabled: true
  Exclude:
    # - Rakefile
    - app/db/migrations/*.rb